bike=["lala","lala2","lala3"]
print(bike)
print(bike[1])
bike.insert(4,"a")
print(bike)
bike.insert(5,"c")
print(bike)
bike.insert(6,"b")
print(bike)
bike.append("ajkdhaiudqwiehjkzchiuzxuciadqiwe")
print(bike)
bike.sort()
print(bike)
bike.remove("lala2")
print(bike)
del bike[1]
print(bike)
bikePoped=bike.pop()
print("poped = "+bikePoped)
print(bike)
bike.reverse()
print(bike)
#lista dentro de lista
bike2=[]
bike2.append("blblbl")
bike2.append("13891iado")
bike2.append("qoq")
bike.append(bike2)
print(bike)
print(bike[4][2])
print("tamanho da lista = "+str(len(bike)))
print("tamanho da lista dentro da lista = "+str(len(bike[4])))
bike.append(1)
print(bike)
bike.sort()
print(bike)
bike2.append(52)
print(bike2)
print(bike)
bike2.sort()
print(bike)