# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_delete_teste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topico'},
        ),
    ]
