# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'entrada'},
        ),
    ]
